AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  OverfastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 1024
      Timeout: 30
      Architectures:
        - arm64   # <-- Correctly specify ARM64 architecture here
      Events:
        ApiEvent:
          Type: HttpApi
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: python3.12-arm64
